### ISSUE TITLE
Support for Classic Mode, Pants Mode & Baby Mode.

### ISSUE THREAD

**Issue by Sigilmare** [Dadido3/D3bot#104]
AFAIK the bots get set at the gamemode's classes the first time they spawn, but then they reroll which breaks the entire point of these modes inside of Zombie Survival.

This should be pretty easy to fix, I may get around to experimenting things to resolve this issue.

**Comment by Dadido3** [comment]
The class reroll is done in here:

https://github.com/Dadido3/D3bot/blob/b1ad7b825ac565f9ea5dc5b913d30fb38d4eea78/lua/d3bot/sv_extend_player.lua#L98-L116

There are already some exceptions, which i don't know how well they work.
But normally you only have to add:

``` lua
if GAMEMODE.IsClassicMode() then return end
if GAMEMODE.IsBabyMode() then return end
if GAMEMODE.PantsMode then return end
```

to support these modes.

**Comment by Sigilmare** [comment]
Done. #105
