### ISSUE TITLE
BotUpdateDelay

### ISSUE THREAD

**Issue by ComradeBlue1337** [Dadido3/D3bot#106]
"[d3bot] addons/d3bot/lua/d3bot/sv_zs_bot_handler/supervisor.lua:142: attempt to perform arithmetic on field 'BotUpdateDelay' (a nil value)
  1. SupervisorThinkFunction - addons/d3bot/lua/d3bot/sv_zs_bot_handler/supervisor.lua:142
   2. fn - addons/d3bot/lua/d3bot/sv_zs_bot_handler/handle.lua:66
    3. unknown - lua/ulib/shared/hook.lua:109 (x428)"

Just booted up the game with the latest version of D3bot and this happens nonstop. Not sure if a typo was made there

**Comment by Dadido3** [comment]
Yeah, there were missing default values for new config options that were added recently. It's fixed now
