### ISSUE TITLE
Seemingly dysfunctional on Linux (Ubuntu Server)

### ISSUE THREAD

**Issue by piqey** [Dadido3/D3bot#113]
Not really much information I can give here. The addon appears to mount fine like all the others, no errors in the console log. The D3bot global table doesn't exist when all's loaded and it's as if the addon never attempted loading in the first place. Admittedly, it's my first time setting up a Garry's Mod server on Linux, but everything else has worked fine up until this point.

It's a shot in the dark, but I know Linux handles file encoding differently than Windows, and I noticed at least one instance of D3bot actually using emojis in Lua, which screams "incompatibility" at me.

Either way, I reckon I've no options left other than filing an issue here and seeing if you have any ideas, @Dadido3

**Comment by Dadido3** [comment]
Hi,

I don't expect it to be the emojis, as Lua doesn't really care about the encoding. It interprets any strings as series of bytes, and only cares about ASCII symbols (0-126) and will happily interpret bytes from any ASCII compatible codepages like Windows-125x, ISO 8859-2, or encodings like UTF-8. So, as long as there are no non ASCII symbols in networked strings and such it will not be a problem.

Different new line characters, and case sensitivity of filenames may be a problem on linux. I'll create a test setup on linux and take a look at this soon.

**Comment by piqey** [comment]
Got it, and I really appreciate it. I'm hoping it's just some mistake I
made somewhere along the line. I am currently using the `x86-64` branch of
server but I'm pretty certain I tried with the release branch as well.

**Comment by piqey** [comment]
> Did you directly used git clone? Because the repository is called `D3bot`, but the addon expects a lowercase `d3bot` for the addon folder. You may just need to rename the addon folder.

welp. problem solved. thank you for the big save <3

**Comment by Dadido3** [comment]
I probably should check how `include` and that `AddCSLuaFile` stuff exactly works, maybe there is a way to get everything independent of the addon directory name. It's not the first time someone has had problems with this.

But good that it's working for you now.

**Comment by piqey** [comment]
> I probably should check how `include` and that `AddCSLuaFile` stuff exactly works, maybe there is a way to get everything independent of the addon directory name. It's not the first time someone has had problems with this.
> 
> But good that it's working for you now.

Yeah, I know that the client and server builds for Linux have loads of weird quirks to them, like file loading order is descending rather than ascending, and file/directory names are case-sensitive on Linux, unlike Windows. I just didn't even think to check if you were including `d3bot` or `D3bot`.

**Comment by piqey** [comment]
So it looks like the only way this could even be fixed on the addon's end would be to rename it to be all lowercase characters, as it appears to be an issue with Garry's Mod's Linux build. The game adds a lowercase version of the paths of each of the addon directories to the mount list, and when the time comes to mount them the OS can't find them because the game is trying to include files using the lowercase path and Linux is case-sensitive in that situation. So for Facepunch to fix the problem, all they'd have to do is stop converting the addon paths to lowercase.

**Comment by Dadido3** [comment]
Well, or i could create releases that contain the correctly named directory.

Then it would still be problematic if you clone the repo. But every normal user that downloads the addon's release archive and unpacks it into their addon folder would be fine...

That's probably the way to go, regardless if i also change the repo's name to lowercase.
