### ISSUE TITLE
Game still selects player as zombie, game can't start

### ISSUE THREAD

**Issue by coolivan8** [Dadido3/D3bot#140]
For some reason when I load the game on my dedicated server, the bots spawn on the zombies team but don't get picked as zombies; this causing the game to be stuck at 0:00 and not starting. I am also playing on zombie survival 2014 on the workshop, but the original gamemode is even worse; I can't even use my weapons for some reason when the bots are added to the game.
![Screenshot (108)](https://github.com/user-attachments/assets/d40fe81c-a271-4ebc-992a-bb75c130cacf)
![Screenshot (109)](https://github.com/user-attachments/assets/e7b56b95-eb52-43b9-846c-30266bec9956)

**Comment by coolivan8** [comment]
it seems it was conflicting addons, don't know which one but I'm going to find it.

**Comment by Dadido3** [comment]
Thanks for the quick correction, feel free to list the conflicting addons when you figured them out.

**Comment by coolivan8** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2266863830
it seems that this mod and the minigame packs that come along with it are the ones that conflict with this addon.
