### ISSUE TITLE
D3Bot does not load in Linux

### ISSUE THREAD

**Issue by arthurgeron** [Dadido3/D3bot#22]
D3Bot apparently does not load on Linux.
I've it set up in addons, navmeshes in `garrysmod/data/d3bot/navmesh/map` folder and d3bot will not load.

**Comment by Dadido3** [comment]
I just set up a linux vm, installed everything in there and tested it.

Everything works fine here, and i can't reproduce the bug. I need more information like:
- Version of OS
- Version of ZS
- If you use ULX, are the D3bot commands listed there?
- Are there any errors on the server side?
- What is the folder called that you put in addons?

**Comment by arthurgeron** [comment]
Kernel: 5.0.0-15-generic
OS: Ubuntu 19.04 (tested in actual paid hosts that run linux as well)
Commands not listed in ULX, no errors server side.
My current file structure as asked:
```
garrysmod
└──addons
   └──D3bot
└──data
     └──d3bot
	└── navmesh
	    └── map
		├── cs_chaves_css_v1.txt
		├── gm_construct.params.txt
		├── gm_construct.txt
		├── gm_flatgrass.params.txt
		[...etc]
```

**Comment by arthurgeron** [comment]
Installed proper libraries, trying again..

**Comment by arthurgeron** [comment]
Same result. If you want I can give you the dev server IP, you have me on your friends list, I'll message you.

**Comment by Dadido3** [comment]
you have rename it to lowercase `d3bot` in your addons folder

**Comment by arthurgeron** [comment]
yes, that fixed it, thank you!
