### ISSUE TITLE
Make D3bot more optimized

### ISSUE THREAD

**Issue by kamielski** [Dadido3/D3bot#32]
when there are a lot of bots on my server the server starts lagging and it also starts lagging when there are a lot of bots inside each other

**Comment by Blueberryy** [comment]
D3 don't have much time todo that, but its planned.

**Comment by kamielski** [comment]
ok

**Comment by kamielski** [comment]
i hope he  will do it soon

**Comment by Dadido3** [comment]
> starts lagging when there are a lot of bots inside each other

This sounds like a gamemode problem.
I'll close this issue, all future speed improvements will be tracked with issue #57.
