### ISSUE TITLE
gm_construction map spawn 8 bot every other map normal

### ISSUE THREAD

**Issue by Light99Z** [Dadido3/D3bot#35]
gm_construction map spawn 8 bot the only way to fix was to put -7 to the bot mod but then every time the map change it will just put 0

**Comment by Blueberryy** [comment]
Clear and save file
d3bot/data/d3bot/navmesh/map/gm_construct.params.txt
Botmod = 7 in file makes 7 bots

**Comment by Dadido3** [comment]
Or use these three commands when you are on gm_construct:
- `!bot setmapparam botmod`
- `!bot setmapparam spp`
- `!bot setmapparam sca`

This will reset the map specific parameters that are pre set for gm_construct.
