### ISSUE TITLE
Bots dying randomly

### ISSUE THREAD

**Issue by Sidevolt** [Dadido3/D3bot#48]
When I spawn bots in, the human bots always kill themselves after short, random time periods and go zombie. They don't stop though, and the zombies kill themselves too and it lags my server hard. I've tried redeeming them, but they suicide again. Is there any way to fix this?

**Comment by Dadido3** [comment]
Does this also happen on an vanilla version of ZS without any other mods/addons (beside ULX)?
Normally survivor bots don't suicide, they only do so if the desired number of survivors is smaller than the actual number.

How have you spawned those survivor bots? Or are you testing on gm_construct where the default is 5+ survivors?

**Comment by Sidevolt** [comment]
I tried using only ULX, ULIB, and ZS ULX Commands, but they kept killing themselves. I was testing this on zs_vertigo, do the bots have issues with objective maps? Also, if it's important I set the SPP to 3, the SCA to 3, and the ZPH to 2. Then I spawned 10 bots using "!botmod 10", and they all killed themselves.

**Comment by Blueberryy** [comment]
Check sv_options and make sure D3bot.SurvivorsEnabled is true

**Comment by Sidevolt** [comment]
Where do I find sv_options?

**Comment by Blueberryy** [comment]
D3bot/lua/d3bot/sv_config.lua 36 line

**Comment by Sidevolt** [comment]
I feel stupid now. I literally just had to go to D3bot-master, and I spent literally half a day trying to figure out where the file was. So anyways, the zombie bots aren't killing themselves unless they get stuck, which is a great improvement, but the human bots always kill themselves after a second, even with SurvivorsEnabled being true.

**Comment by HordeStick** [comment]
Late reply, but i've never had this issue.
