### ISSUE TITLE
node drawing distance

### ISSUE THREAD

**Issue by kamielski** [Dadido3/D3bot#50]
make a node drawing distance that you can configure for like big maps where you see a lot of nodes

**Comment by Dadido3** [comment]
Is `d3bot_navmeshing_smartdraw` enabled on your client? It should be enabled by default, but you never know. Smartdraw helps by not drawing any obscured nodes.

But i can see how it could help for large flat maps. I'll create a branch with the needed changes soon, i just wont be able to test it here right now, so i would like some feedback if it works and if it doesn't have any strange sideeffects.

**Comment by Dadido3** [comment]
Check out 175b1fe55903ed3dbfb9f2f7031ef77caf809ff5 inside the branch drawingDistance.

If it works well, i'll put it into master

**Comment by kamielski** [comment]
I have smartdraw enabled but sometimes on big maps, there are a lot of nodes so my fps goes down

**Comment by Dadido3** [comment]
Then download the [drawDistance branch]https://github.com/Dadido3/D3bot/tree/drawingDistance), and if it works well, i'll publish it officially. Also i forgot to mention the console command:

- `d3bot_navmeshing_drawdistance 100` to limit drawing to 100 source engine units.
- `d3bot_navmeshing_drawdistance 0` to disable the limit.

**Comment by kamielski** [comment]
ok thanks
