### ISSUE TITLE
New type of node needed to allow bots to path only on a certain wave

### ISSUE THREAD

**Issue by DessertOverlord** [Dadido3/D3bot#63]
Some maps (in particular, abandoned_mall_v6s) have doors that only open on a specific wave number, and currently, there isn't a parameter to add this to bot behavior.

**Comment by Dadido3** [comment]
I'll add a parameter for it when i find some time.

For now you have to use `condition = unblocked` to prevent bots from using this node in paths, as long as the door exists. And rely on human undead players to destroy that door manually.
