### ISSUE TITLE
Update about invisible bots.

### ISSUE THREAD

**Issue by HordeStick** [Dadido3/D3bot#74]
The bug is caused by the zombies that use CLASS.OverrideModel along with an alpha. For example, the Shadow Walker or Frigid Revenant in 2018 zs. This bug only happens when bots can be those zombies. To be honest, it happens with any zombie class that uses CLASS.OverrideModel. For some reason, the overridden model would just freeze in the air with a t-pose and the bot would be invisible. Not sure how this is fixable, i guess bots just can't be these zombie classes...

**Comment by Dadido3** [comment]
Thanks for the information, maybe i can use it to find a fix.

Next time add to the already existing issue #69. Just to keep everything clean. I'll close this one and link it.

**Comment by HordeStick** [comment]
KK cheers
