### ISSUE TITLE
Disable anti-skycade

### ISSUE THREAD

**Issue by njawoo** [Dadido3/D3bot#78]
Hey, i'm looking to disable the anti-skycade function. It's clearly in D3bot as removing the folder removed it, but i can't find an option in the files

**Comment by Dadido3** [comment]
I assume you mean the damage that can be defined on nodes. Just remove the following lines of code from your version:
https://github.com/Dadido3/D3bot/blob/d085190457b47e84eb7540a5d19b4dbb6ac90884/lua/d3bot/sv_zs_bot_handler/supervisor.lua#L146-L148

There is no option to disable it globally for now.

**Comment by njawoo** [comment]
> 
> 
> I assume you mean the damage that can be defined on nodes. Just remove the following lines of code from your version:
> 
> https://github.com/Dadido3/D3bot/blob/d085190457b47e84eb7540a5d19b4dbb6ac90884/lua/d3bot/sv_zs_bot_handler/supervisor.lua#L146-L148
> 
> There is no option to disable it globally for now.

Thank you so much!
