### ISSUE TITLE
No bots spawn.

### ISSUE THREAD

**Issue by SpongySponge** [Dadido3/D3bot#81]
I played on avaliable maps at correct versions i did the command and bots didnt spawn it said that it changed but nothing changed no bots have spawned can this be fixed.

**Comment by Dadido3** [comment]
This can have all sorts of reasons, i need some more information:

- What is "the command", what was the message you got?
- Is your gamemode Zombie survival?
- Have you installed the addon correctly? Could you tell me the full path of `lua/d3botsv_config.lua` for example?
- Did you move the navmeshes from the addon to your gmod data folder?

**Comment by SpongySponge** [comment]
woops sry i didnt go through the installation correctly

**Comment by Dadido3** [comment]
Alright, gonna close this issue then.
