### ISSUE TITLE
Survivor Bots

### ISSUE THREAD

**Issue by Pomrgite** [Dadido3/D3bot#90]
Bots-survivors die after a couple of seconds, then new ones appear and die in the same way.
In the settings is
D3bot.SurvivorsEnabled = True
help me!

**Comment by Dadido3** [comment]
You also need to set the allowed number of survivor bots. To adjust it globally, change the `D3bot.SurvivorsPerPlayer = 0` and/or `D3bot.SurvivorCountAddition = 0` fields.

And you can also adjust the number of survivor bots per map: `SCA` map parameter.

**Comment by Pomrgite** [comment]
D3bot.SurvivorsPerPlayer = 1.2
Still not work

**Comment by Dadido3** [comment]
Does it not even work if you set `D3bot.SurvivorCountAddition = 5`?

**Comment by Pomrgite** [comment]
again - nothing
Dropped Bot17 from server (No reason given)
Dropped Bot18 from server (No reason given)
Dropped Bot19 from server (No reason given)
Dropped Bot20 from server (No reason given)
Dropped Bot21 from server (No reason given)
Dropped Bot22 from server (No reason given)
Dropped Bot23 from server (No reason given)
Dropped Bot24 from server (No reason given)

**Comment by Pomrgite** [comment]
On any zs version i got this shi-

**Comment by Dadido3** [comment]
Now you are saying they are dropped/kicked from the server, did you redeem the bots, or are you just spawning new bots? Also, did you change any other settings? And does a map restart help?

**Comment by Pomrgite** [comment]
nvm, I solved the problem, all because of one script, thanks:^)

**Comment by Dadido3** [comment]
alright
